# Generated by Django 5.0.1 on 2026-04-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_enterprise_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('boutique', 'Boutique'), ('pharmacie', 'Pharmacie'), ('salon_coiffure', 'Salon de coiffure')], default='boutique', max_length=32),
        ),
    ]
