# Generated by Django 5.0.1 on 2026-04-16 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('school_admin', 'School admin'), ('admin', 'Admin'), ('seller', 'Seller'), ('cashier', 'Cashier')], default='seller', max_length=32),
        ),
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=128)),
                ('event_type', models.CharField(blank=True, default='api_call', max_length=64)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('status_code', models.PositiveIntegerField(default=0)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('payload_preview', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='users_admin_created_8d4a0e_idx'), models.Index(fields=['event_type', 'created_at'], name='users_admin_event_t_04e5f8_idx'), models.Index(fields=['tenant_id', 'created_at'], name='users_admin_tenant__4e6cf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(blank=True, default='', max_length=128)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('is_web', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('last_ip', models.CharField(blank=True, default='', max_length=64)),
                ('last_user_agent', models.TextField(blank=True, default='')),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['last_seen_at'], name='users_userh_last_se_52f0a6_idx'), models.Index(fields=['tenant_id', 'last_seen_at'], name='users_userh_tenant__16361e_idx'), models.Index(fields=['user', 'device_id'], name='users_userh_user_id_718b08_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
