# Generated by Django 5.0.1 on 2026-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role_adminauditevent_userheartbeat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userheartbeat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userheartbeat',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('cashier', 'Cashier')], default='seller', max_length=32),
        ),
        migrations.DeleteModel(
            name='AdminAuditEvent',
        ),
        migrations.DeleteModel(
            name='UserHeartbeat',
        ),
    ]
