KINSHASA_LOCATIONS = {
    "Bandalungwa": ["Bisengo", "Disasi", "Joli Parc", "Makelele", "Mayoyo", "Moulaert"],
    "Barumbu": ["Bon Marché", "Dendale", "Fonio", "Libulu", "Mongala", "Yolo Nord"],
    "Bumbu": ["Dipiya", "Lemfu", "Mfidi", "Mikondo", "Mwadi", "Nsanga"],
    "Gombe": ["Batetela", "Commerce", "Croisement", "Golf", "Haut Commandement", "Socimat"],
    "Kalamu": ["Funa", "Immo Congo", "Kauka", "Matonge", "Yolo Centre", "Yolo Sud"],
    "Kasa-Vubu": ["Assossa", "Bonga", "Luvua", "Mokali", "Ngiri-Ngiri Frontière", "RVA"],
    "Kimbanseke": ["Bambole", "Biyela", "Kingasani", "Kisenso Gare", "Makala", "Mokali"],
    "Kinshasa": ["Boyoma", "Dahomey", "Feshi", "Mongala", "Plateau", "Wenze"],
    "Kintambo": ["ITI", "Kintambo Magasin", "Lubudi", "Nganda", "Siforco", "Socimat Kintambo"],
    "Kisenso": ["Amba", "Kisenso Gare", "Libération", "Mokali", "Mukala", "Regideso"],
    "Lemba": ["Commerciale", "Foire", "Livulu", "Masano", "Righini", "Salongo"],
    "Limete": ["1ère Rue", "10ème Rue", "Industriel", "Kingabwa", "Mombele", "Résidentiel"],
    "Lingwala": ["Beau Vent", "Camp Luka", "Croix-Rouge", "Huileries", "Maniema", "Météo"],
    "Makala": ["Mabulu", "Mavula", "Mbankana", "Mokali", "Songa", "Tshikapa"],
    "Maluku": ["Bateke", "Buma", "Ibi", "Kimpoko", "Mbankana", "Mongata"],
    "Masina": ["Abattoir", "Bitabe", "Mapela", "Petro Congo", "Sans Fil", "Siforco"],
    "Matete": ["Kinsiona", "Lufu", "Mokali", "Mutoto", "Sao", "Talangai"],
    "Mont-Ngafula": ["Cité Pumbu", "Kimwenza", "Kindele", "Mama Mobutu", "Masanga-Mbila", "Mitendi"],
    "Ndjili": ["1", "2", "3", "4", "5", "7"],
    "Ngaba": ["Baobab", "Bulambemba", "Luyi", "Mateba", "Mpila", "Mukuna"],
    "Ngaliema": ["Binza Delvaux", "Binza Météo", "Joli Site", "Ma Campagne", "Mbinza Ozone", "Utexafrica"],
    "Ngiri-Ngiri": ["24 Novembre", "Kasaï", "Maman Yemo", "Munkamba", "Sampwe", "Wenze ya Ngiri"],
    "Nsele": ["Bibwa", "Kinkole", "Mikonga", "Mpassa", "N'sele Mission", "Tchangu"],
    "Selembao": ["Badiadingi", "Herady", "Kalunga", "Kipe", "Luyayi", "Meteo Selembao"],
}

BUSINESS_DOMAINS = [
    ("restaurant", "Restaurant"),
    ("pharmacy", "Pharmacy"),
    ("boutique", "Boutique"),
    ("supermarket", "Supermarket"),
    ("hardware", "Quincaillerie"),
    ("cosmetics", "Cosmetiques"),
    ("electronics", "Electronique"),
    ("other", "Autre"),
]
