from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import (
    AccountingReportsView,
    AdminForceLogoutGlobalView,
    AdminPlatformOverviewView,
    AdminSellersActivityView,
    AdminTenantStatusUpdateView,
    AdminTenantDetailView,
    AdminTenantsListView,
    AdminTenantsCsvExportView,
    CustomerViewSet,
    CustomersSummaryView,
    InsightsView,
    NearbySuppliersView,
    SupplierMarketplaceView,
    ProductViewSet,
    AiSaleDraftView,
    QuickSaleCreateView,
    ReceiptVerifyView,
    SalesListView,
    SalesSummaryView,
    StockAddView,
    StockMovementsView,
    StockOverviewView,
    SupplierProductListCreateView,
    SupplierProfileView,
    SupplierOrderListCreateView,
    SupplierOrderStatusUpdateView,
    SupplierCallStartView,
    SupplierCallEndView,
    SupplierImageUploadView,
    SupplierAudioUploadView,
    SupplierFileUploadView,
    KinshasaLocationsView,
    SupplierConversationListCreateView,
    SupplierConversationMessagesView,
    SupplierQuickOrderCreateView,
)

router = DefaultRouter()
router.register("products", ProductViewSet, basename="commerce-product")
router.register("customers", CustomerViewSet, basename="commerce-customer")

urlpatterns = [
    path("admin/overview/", AdminPlatformOverviewView.as_view(), name="commerce-admin-overview"),
    path("admin/sellers-activity/", AdminSellersActivityView.as_view(), name="commerce-admin-sellers-activity"),
    path("admin/tenants/", AdminTenantsListView.as_view(), name="commerce-admin-tenants"),
    path("admin/tenants/<str:tenant_id>/", AdminTenantDetailView.as_view(), name="commerce-admin-tenant-detail"),
    path("admin/tenants/<str:tenant_id>/status/", AdminTenantStatusUpdateView.as_view(), name="commerce-admin-tenant-status"),
    path("admin/force-logout/", AdminForceLogoutGlobalView.as_view(), name="commerce-admin-force-logout"),
    path("admin/export/tenants.csv", AdminTenantsCsvExportView.as_view(), name="commerce-admin-export-tenants-csv"),
    path("customers/summary/", CustomersSummaryView.as_view(), name="commerce-customers-summary"),
    path("insights/", InsightsView.as_view(), name="commerce-insights"),
    path("accounting/reports/", AccountingReportsView.as_view(), name="commerce-accounting-reports"),
    path("stock/overview/", StockOverviewView.as_view(), name="commerce-stock-overview"),
    path("stock/add/", StockAddView.as_view(), name="commerce-stock-add"),
    path("stock/movements/", StockMovementsView.as_view(), name="commerce-stock-movements"),
    path("suppliers/my-profile/", SupplierProfileView.as_view(), name="commerce-suppliers-my-profile"),
    path("suppliers/my-products/", SupplierProductListCreateView.as_view(), name="commerce-suppliers-my-products"),
    path("suppliers/nearby/", NearbySuppliersView.as_view(), name="commerce-suppliers-nearby"),
    path("suppliers/marketplace/", SupplierMarketplaceView.as_view(), name="commerce-suppliers-marketplace"),
    path("suppliers/kinshasa-locations/", KinshasaLocationsView.as_view(), name="commerce-suppliers-kinshasa-locations"),
    path("suppliers/orders/", SupplierOrderListCreateView.as_view(), name="commerce-suppliers-orders"),
    path("suppliers/orders/quick/", SupplierQuickOrderCreateView.as_view(), name="commerce-suppliers-orders-quick"),
    path("suppliers/orders/<int:order_id>/status/", SupplierOrderStatusUpdateView.as_view(), name="commerce-suppliers-order-status"),
    path("suppliers/calls/start/", SupplierCallStartView.as_view(), name="commerce-suppliers-call-start"),
    path("suppliers/calls/end/", SupplierCallEndView.as_view(), name="commerce-suppliers-call-end"),
    path("suppliers/upload-image/", SupplierImageUploadView.as_view(), name="commerce-suppliers-upload-image"),
    path("suppliers/upload-audio/", SupplierAudioUploadView.as_view(), name="commerce-suppliers-upload-audio"),
    path("suppliers/upload-file/", SupplierFileUploadView.as_view(), name="commerce-suppliers-upload-file"),
    path("suppliers/conversations/", SupplierConversationListCreateView.as_view(), name="commerce-suppliers-conversations"),
    path("suppliers/conversations/<int:conversation_id>/messages/", SupplierConversationMessagesView.as_view(), name="commerce-suppliers-conversation-messages"),
    path("sales/summary/", SalesSummaryView.as_view(), name="commerce-sales-summary"),
    path("sales/ai-draft/", AiSaleDraftView.as_view(), name="commerce-sales-ai-draft"),
    path("sales/list/", SalesListView.as_view(), name="commerce-sales-list"),
    path("sales/receipt-verify/", ReceiptVerifyView.as_view(), name="commerce-sales-receipt-verify"),
    path("sales/quick/", QuickSaleCreateView.as_view(), name="commerce-sales-quick"),
]

urlpatterns += router.urls
